# Generated by Django 4.2.7 on 2023-12-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Ingredientname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('Recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Recipename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restourant',
            fields=[
                ('resto_id', models.IntegerField(primary_key=True, serialize=False)),
                ('resto_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restourant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.restourant')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='Restourant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.restourant'),
        ),
    ]
