# Generated by Django 4.2.7 on 2023-12-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
