# Generated by Django 4.2.7 on 2023-12-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0002_recipeingredient_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient_name',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe_name',
        ),
    ]
